create database project;

CREATE TABLE project.sales (
    Store INT,
    Dept INT,
    Date DATE,
    Weekly_Sales DOUBLE,
    IsHoliday BOOLEAN,
    PRIMARY KEY (Store, Dept, Date)
);

CREATE TABLE project.stores (
    Store INT PRIMARY KEY,
    Type CHAR(1),
    Size INT
);

CREATE TABLE project.features (
    Store INT,
    Date DATE,
    Temperature DECIMAL(5, 2),
    Fuel_Price DECIMAL(5, 3),
    MarkDown1 DOUBLE,
    MarkDown2 DOUBLE,
    MarkDown3 DOUBLE,
    MarkDown4 DOUBLE,
    MarkDown5 DOUBLE,
    CPI DECIMAL(10, 7),
    Unemployment DECIMAL(4, 3),
    IsHoliday BOOLEAN,
    PRIMARY KEY (Store, Date)
);

USE project;

SELECT * FROM features;
SELECT * FROM sales;
SELECT * FROM stores;

-- Questions 
-- 1. What is the date range for the sales data
SELECT min(Date), max(Date) from sales;

-- 2. What is the total revenue generated by each store?
SELECT store, sum(Weekly_Sales) as total_revenue from sales group by store order by sum(Weekly_Sales) desc;

-- Store 20 generates the highest revenue by sales from 2010-2012 

-- 3. What are the top 5 weeks with the highest sales?
SELECT week(date) as week_number, sum(Weekly_Sales) as total_sales from sales group by week(date) order by sum(Weekly_Sales) desc limit 5;

-- Top weeks with highest sales are 51, 22, 7, 27, 14

-- 4. What is the average weekly sales per store type?
SELECT s2.Type as Store_Type, round(avg(s1.Weekly_Sales),2) as avg_weekly_sales 
from sales s1 JOIN stores s2 on s1.Store=s2.Store group by s2.Type order by s2.Type;

-- Which stores had the highest sales on holiday weeks?
SELECT store, sum(Weekly_Sales) as total_revenue from sales where IsHoliday="True" group by store order by sum(Weekly_Sales) desc;
-- Store 20 has the highest sales on holiday weeks 

-- How many stores belong to each store type (A, B, C)?
SELECT Type, count(Store) from stores group by Type;

-- Which stores have the highest markdown discounts?
SELECT Store, round(sum(MarkDown1)+sum(MarkDown2)+sum(MarkDown3)+sum(MarkDown4)+sum(MarkDown5),2) as Markdown_Discount from features group by Store order by Markdown_Discount;

-- What is the average fuel price each month?
SELECT MONTHNAME(Date) as Month, avg(Fuel_Price) from features group by MONTHNAME(Date) order by MONTHNAME(Date);


--  How does unemployment change over time?
SELECT YEAR(Date) as Year, round(avg(Unemployment),2) FROM features group by YEAR(Date);

-- ## Complex Questions

-- * Do markdowns (discounts) significantly increase sales?
with cte as (
SELECT s.store, s.Date, s.Weekly_Sales, f.MarkDown1+f.MarkDown2+f.MarkDown3+f.MarkDown4+f.MarkDown5 as Total_MarkDown, 
(CASE WHEN MarkDown1>0 or MarkDown2>0 or MarkDown3>0 or MarkDown4>0 or MarkDown5>0 THEN "Yes" else "No" end) as Discount
from sales s JOIN features f on s.Store=f.Store and s.Date=f.Date)
SELECT Discount, round(avg(Weekly_Sales),2) from cte group by Discount;
;

-- The average sales on days after discount is higher than the one without discount by 300Rs which is not very significant

-- * What is the impact of holidays on sales performance across different store types?
SELECT s2.Type as "Store_Type", 
ROUND(AVG(CASE WHEN s1.IsHoliday = 'True' THEN s1.Weekly_Sales END) - AVG(CASE WHEN s1.IsHoliday = 'False' THEN s1.Weekly_Sales END)) AS Sales_Difference
FROM sales s1 JOIN stores s2 on s1.Store=s2.Store group by s2.Type;

-- Yes the sales performance increases on the weeks which are holiday across all the three store types with the highest change being for store type A

-- * Which store types (A, B, C) perform best under economic fluctuations (CPI, Unemployment)?
with cte as (
SELECT s.Store, (Case when f.CPI<160 then "Low" else case when f.CPI>=160 and f.CPI<190 then "Medium" else "High" END END) as CPI, (Case when f.Unemployment<7 then "Low" else case when f.Unemployment>=7 and f.Unemployment<10 then "Medium" else "High" END END) as Unemployment
, s.Weekly_Sales from sales s Join features f on s.Store=f.Store and s.Date=f.Date
)
SELECT s.Type as Store_Type, c.CPI, c.Unemployment, round(avg(c.Weekly_Sales),2) as Avg_Sales from cte c 
JOIN stores s on c.Store=s.Store group by s.Type, c.CPI, c.Unemployment order by s.Type, c.CPI, c.Unemployment;

-- * What is the effect of fuel prices on Walmart’s sales trends?
with cte as (
SELECT (case when f.Fuel_Price<=3 then 'Low' else case when f.Fuel_Price>3 and f.Fuel_Price<=4 then 'Mid' else 'High' end end) as Fuel, s.Weekly_Sales
from features f JOIN sales s on f.Store=s.Store and f.Date=s.Date
)
SELECT Fuel, avg(Weekly_Sales) from cte group by Fuel;


-- Give me the number of top three highest performing departments in each store
with cte as (
SELECT Store, Dept, avg(Weekly_Sales) as Average_Sales from sales group by Store, Dept
), 
cte_2 as (
SELECT Store, Dept, Average_Sales, dense_rank() over(partition by Store order by Average_Sales desc) as dept_rank 
from cte group by Store, Dept
)
SELECT Store, Dept, Average_Sales from cte_2 where dept_rank<=3;


